# myfile = open("jaggu.txt","r")
# print("this file contains ")
# print(myfile.read())
# myfile.close()
# myfile = open("jaggu.txt","a")
# myfile.write("\nnonipila")
# myfile.close()
# myfile = open("jaggu.txt","r")
# print("this file ")
# print(myfile.read())
# myfile.close()
myfile = open("jaggu.txt","a")
for i in range(5):
    myfile.write("\nnonipila")
myfile.close()